@startuml
actor Utente as User
participant Client
participant Server

User -> Server: Avvia Applicazione
Client -> Server: Richiesta di Connessione
Client -> Server: connect()
Server --> Client: Connessione Riuscita

Server -> Client: dati iniziali (idClient, x, y, bombaPiazzata)

loop Gioco
    Client -> Server: MovimentoGiocatore(x, y, bombaPiazzata)
    Server -> Client: confermaRicezione()
    Server -> Server: Elabora Coordinate
    Server -> Server: Verifica azione
    Client -> Server: riceviMessaggio()
    Client -> Client: disegna blocco
    Server -> Server: Costruisci Messaggio
    Server -->> Client: Invia Messaggio
end loop

Server -> Client: verifica fine gioco
Client -> Client: schermata vittoria/sconfitta
@enduml